# When enabled, this allows shorter env properties (ex -Dspring.profiles.active=logzio)
spring:
  main:
    # ZipkinLogzioStorageModule overrides the bean named 'storage'
    allow-bean-definition-overriding: true
zipkin:
  internal:
    module:
      logzio: zipkin.module.storage.logzio.ZipkinLogzioStorageModule
  storage:
    logzio:
      logzio-listener-host: ${LOGZIO_LISTENER_HOST:listener.logz.io}
      logzio-api-token: ${LOGZIO_API_TOKEN:}
      logzio-api-host: ${LOGZIO_API_HOST:api.logz.io}
      logzio-account-token: ${LOGZIO_ACCOUNT_TOKEN:}
      sender-drain-interval: ${SENDER_DRAIN_INTERVAL:5}
      clean-sent-traces-interval: ${CLEAN_SENT_TRACES_INTERVAL:30}
